#!/bin/sh

. /lib/preseed/preseed.sh

while true; do
	case "$1" in
	    -C)
		LOOKUP_CHECKSUM=1
		;;
	    -*)
		# eat options starting with a -, so we can pass them on
		OPTS="$OPTS $1"
		;;
	    *)
		break
		;;
	esac
	shift
done

src="$1"
shift

last=/var/run/preseed.last_location
url=$(make_absolute_url "$src" "$(test -r $last && cat $last)")

fetch-url $OPTS "$url" "$@"
