#! /bin/sh

. /usr/share/debconf/confmodule

if db_get auto-install/enable && [ "$RET" = true ]; then
	# disable locale & kbd selection for now
	echo 1 >/var/run/auto-install.active
	# check that no preseed has been specified
	# (DHCP preseed still possible - once net is up, check in auto-install.sh)
	if ! [ -e /preseed.cfg ] &&
	   ! { db_get preseed/url  && [ "$RET" ]; } &&
	   ! { db_get preseed/file && [ "$RET" ]; }; then
		# register that no preseed was specified.
		touch /var/run/preseed_unspecified_at_boot
	fi
fi
